server:
  servlet:
    context-path: /profile
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/database_profile}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:sapassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
